### ISSUE TITLE
New required field with no documentation

### ISSUE THREAD

**Issue by abbydrury** [ebsco/edsapi-drupal8-plugin#52]
I tried to update to the `8.x` branch of this module, and discovered that the "EBSCO settings" page (Configuration > Search and metadata > EBSCO Discovery Service Settings) has a new required field called "Autocomplete". The help text ("The API has Autocomplete.") is not particularly helpful, and you cannot submit the form without providing a value. 

Can you please add some information about what this field should contain to the installation notes in the README files? The picture below shows the field error condition.
![eds_module_required_field](https://user-images.githubusercontent.com/48217815/136088031-7bfc565c-6242-4db8-bac9-83a1e40d2492.png)

**Comment by kelsonthony** [comment]
Hello @abbydrury 
How you going? 
So, autocomplete method is required on EDS API now. 
you can type 'autocomplete' on this label and you will can submit the form. 

Please, could you try this way? 

Thank you.

**Comment by abbydrury** [comment]
That does allow me to submit the form, but the module still doesn't work and throws a ton of errors in dblog as noted in issue #53.

Also, are there other possible values aside from "autocomplete"? If not, why is this a configurable field at all? It might be more user-friendly to hard-code this value in the module and not ask for it as a configuration field at all, make the field optional and default the value to the expected value of "autocomplete" if it is not provided, or make it a pulldown menu if there is a strict vocabulary for the possible options.

**Comment by abbydrury** [comment]
Additionally, I only knew that this new field existed because when I upgraded from 0.2 to 8.1.1, the module was broken, which caused me to hunt down the configuration page for the module. I would suggest that it would be helpful if this new required information was highlighted in the documentation for 8.x and 9.x for any other folks who might be attempting to upgrade from 0.2 to a more modern version of the module.

**Comment by kelsonthony** [comment]
Fixed
